services:
  - type: web
    name: pdf-form-editor-api
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: FRONTEND_ORIGINS
        value: https://yauchinlam.github.io
